name: Ruby Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.4
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Lint
      run: |
        bundle exec standardrb
    - name: Test
      run: |
        bundle exec rspec
